packages:
  - apps/fixtures/*
  - packages/*

allowBuilds:
  '@mongodb-js/zstd': set this to true or false
  node-liblzma: set this to true or false

catalog:
  "@types/node": "24.13.3"
  typescript: "7.0.2"
  vitest: "4.1.10"
  zod: "4.5.4"

minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.3'
  - '@turbo/darwin-arm64@2.11.3'
  - '@turbo/linux-64@2.11.3'
  - '@turbo/linux-arm64@2.11.3'
  - '@turbo/windows-64@2.11.3'
  - '@turbo/windows-arm64@2.11.3'
  - turbo@2.11.3
  - eve@0.64.1
